# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (4)
# #########################################################################

class Author(BaseModel):
    prefix: typing.Optional[str] = None
    first_name: str
    last_name: str

class CitationInfo(BaseModel):
    authors: typing.List["Author"]
    url: str
    article_title: str
    publication_title: str
    publication_date: "Date"
    access_date: "Date"
    volume: typing.Optional[str] = None
    issue: typing.Optional[str] = None
    page_range: typing.Optional[str] = None
    doi: typing.Optional[str] = None

class Date(BaseModel):
    day: str
    month: str
    year: str

class Website(BaseModel):
    url: str
    content: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
