# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class Author(BaseModel):
    prefix: typing.Optional[str] = None
    first_name: typing.Optional[str] = None
    last_name: typing.Optional[str] = None

class CitationInfo(BaseModel):
    authors: typing.List["Author"]
    url: typing.Optional[str] = None
    article_title: typing.Optional[str] = None
    website_title: typing.Optional[str] = None
    publication_date: typing.Optional["Date"] = None
    access_date: typing.Optional["Date"] = None
    volume: typing.Optional[str] = None
    issue: typing.Optional[str] = None
    page_range: typing.Optional[str] = None
    doi: typing.Optional[str] = None

class Date(BaseModel):
    day: typing.Optional[str] = None
    month: typing.Optional[str] = None
    year: typing.Optional[str] = None

class Website(BaseModel):
    url: typing.Optional[str] = None
    content: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
