# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class CitationInfo(BaseModel):
    authors: typing.List[str]
    url: typing.Optional[str] = None
    title: typing.Optional[str] = None
    publication_date: typing.Optional["Date"] = None
    access_date: typing.Optional["Date"] = None
    doi: typing.Optional[str] = None

class Date(BaseModel):
    day: typing.Optional[int] = None
    month: typing.Optional[int] = None
    year: typing.Optional[int] = None

class Website(BaseModel):
    url: typing.Optional[str] = None
    content: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
