# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CitationInfo": types.CitationInfo,
    "stream_types.CitationInfo": stream_types.CitationInfo,

    "types.Date": types.Date,
    "stream_types.Date": stream_types.Date,

    "types.Website": types.Website,
    "stream_types.Website": stream_types.Website,


}